Add parallel_reduce dynamic sized elements of View
ORNL-CEES/kokkos pull request #25
Opened 2020-01-07 18:56 UTC by Rombur

With this PR, all the reduction tests are passing.

2020-01-07 21:06 UTC, dalg24 requested changes

2020-01-07 21:06 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_ReduceScan.hpp
> +  if (BlockSizeMask & blockDim.y) {
`hipBlockDim_y`?

2020-01-07 21:06 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_ReduceScan.hpp
> +  const unsigned rtid_intra      = threadIdx.y ^ BlockSizeMask;
`hipThreadIdx_x`?

2020-01-07 21:06 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_ReduceScan.hpp
> +  const pointer_type tdata_intra = base_data + value_count * threadIdx.y;
`hipThreadIdx_y`

2020-01-07 21:06 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_ReduceScan.hpp
> +      if (DoScan) {
Maybe comment that runtime check could be avoided.

2020-01-07 21:06 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_ReduceScan.hpp
> +__device__ bool hip_single_inter_block_reduce_scan2(
I was going to complain about the name but I guess that is copied from Cuda :/

2020-01-07 21:06 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_ReduceScan.hpp
> +  bool const is_last_block = n_done == block_count ? true : false;
Why the ternary operator?

2020-01-08 14:42 UTC, Rombur commented
Fixed

2020-01-08 15:37 UTC, dalg24 approved these changes

2020-01-08 21:22 UTC, merged